export { CLI_NAME, NPM_PACKAGE_NAME, PREFERRED_NAME } from "./names.js";
export {
  installInitYes,
  preflightForceRefresh,
  mergeHooksJson,
  stripAutopilotHooks,
  countAutopilotDuplicates,
  validateHooksShape,
  hasCompleteAutopilotHooks,
  summarizeAutopilotHooks,
  autopilotStopHasUnlimitedLoop,
  autopilotHookCommand,
  mergeClaudeSettings,
  validateClaudeSettingsShape,
  hasClaudeBlockCapZero,
  hasCompleteClaudeAutopilotHooks,
  summarizeClaudeAutopilotHooks,
  stripAutopilotClaudeSettings,
  claudeSettingsContainAutopilot,
  CLAUDE_AUTOPILOT_EVENTS,
  CLAUDE_BLOCK_CAP_ENV,
  mergeCodexHooks,
  validateCodexHooksShape,
  hasCompleteCodexAutopilotHooks,
  summarizeCodexAutopilotHooks,
  stripAutopilotCodexHooks,
  codexHooksContainAutopilot,
  codexHooksHavePlatformStamp,
  codexAutopilotHasSmallTimeout,
  CODEX_AUTOPILOT_EVENTS,
  CODEX_POST_TOOL_USE_MATCHER,
  mergeCopilotHooks,
  validateCopilotHooksShape,
  hasCompleteCopilotAutopilotHooks,
  summarizeCopilotAutopilotHooks,
  stripAutopilotCopilotHooks,
  copilotHooksContainAutopilot,
  copilotHooksHavePlatformStamp,
  copilotAutopilotHasSmallTimeout,
  COPILOT_AUTOPILOT_EVENTS,
  COPILOT_POST_TOOL_USE_MATCHER,
  COPILOT_HOOK_TIMEOUT_SEC,
  COPILOT_HOOKS_REL_PATH,
  mergeGrokHooks,
  validateGrokHooksShape,
  hasCompleteGrokAutopilotHooks,
  summarizeGrokAutopilotHooks,
  stripAutopilotGrokHooks,
  grokHooksContainAutopilot,
  grokHooksHavePlatformStamp,
  grokAutopilotHasOmittedOrSmallTimeout,
  grokHooksFileIsVacant,
  GROK_AUTOPILOT_EVENTS,
  GROK_POST_TOOL_USE_MATCHER,
  GROK_HOOK_TIMEOUT_SEC,
  GROK_HOOKS_REL_PATH,
  mergeGeminiSettings,
  validateGeminiSettingsShape,
  hasCompleteGeminiAutopilotHooks,
  summarizeGeminiAutopilotHooks,
  stripAutopilotGeminiSettings,
  geminiSettingsContainAutopilot,
  geminiSettingsHaveForeignContent,
  geminiSettingsFileIsVacant,
  geminiHooksHavePlatformStamp,
  geminiAutopilotHasSmallTimeout,
  geminiHooksConfigEnabledIsFalse,
  geminiAutopilotNamesInHooksConfigDisabled,
  GEMINI_AUTOPILOT_EVENTS,
  GEMINI_AFTER_TOOL_MATCHER,
  GEMINI_HOOK_TIMEOUT_MS,
  GEMINI_WILDCARD_MATCHER,
  GEMINI_HOOK_NAME_PREFIX,
  GEMINI_SETTINGS_REL_PATH,
  mergeKimiConfigToml,
  stripAutopilotKimiHooks,
  removeAutopilotKimiHooks,
  kimiHooksContainAutopilot,
  kimiTomlHasAutopilotHookTables,
  kimiTomlHasDroppableAutopilotHooks,
  kimiHooksHavePlatformStamp,
  kimiAutopilotMissingEvents,
  kimiAutopilotMissingHookEvents,
  kimiAutopilotHasSmallTimeout,
  resolveKimiCodeHome,
  kimiConfigTomlPath,
  readKimiConfigToml,
  KIMI_AUTOPILOT_EVENTS,
  KIMI_POST_TOOL_USE_MATCHER,
  KIMI_HOOK_TIMEOUT_SEC,
  mergeHermesConfig,
  mergeHermesConfigYaml,
  stripAutopilotHermesHooks,
  stripAutopilotHermesConfigYaml,
  hermesHooksContainAutopilot,
  hermesConfigYamlContainsAutopilot,
  hermesHooksHavePlatformStamp,
  hermesAutopilotHasOmittedOrSmallTimeout,
  hermesAutopilotHasExpectedPostMatcher,
  hasCompleteHermesAutopilotHooks,
  summarizeHermesAutopilotHooks,
  hermesHooksBlockIsVacant,
  hermesConfigHasVerifyNudgeFloor,
  ensureHermesMaxVerifyNudges,
  resolveHermesHome,
  hermesConfigYamlPath,
  readHermesConfigYaml,
  parseHermesConfigYaml,
  formatHermesConfigYaml,
  autopilotHermesHookEntry,
  HERMES_AUTOPILOT_EVENTS,
  HERMES_POST_TOOL_MATCHER,
  HERMES_HOOK_TIMEOUT_SEC,
  HERMES_MAX_VERIFY_NUDGES,
  HERMES_CONFIG_REL_PATH,
  mergeDevinHooks,
  validateDevinHooksShape,
  hasCompleteDevinAutopilotHooks,
  summarizeDevinAutopilotHooks,
  stripAutopilotDevinHooks,
  devinHooksContainAutopilot,
  devinHooksHavePlatformStamp,
  devinAutopilotHasOmittedOrSmallTimeout,
  devinHooksFileIsVacant,
  devinHooksUseProjectDirEnv,
  devinConfigJsonContainsAutopilot,
  autopilotDevinHookCommandLine,
  autopilotDevinMatcherGroup,
  DEVIN_AUTOPILOT_EVENTS,
  DEVIN_POST_TOOL_USE_MATCHER,
  DEVIN_HOOK_TIMEOUT_SEC,
  DEVIN_HOOKS_REL_PATH,
  DEVIN_CONFIG_REL_PATH,
  DEVIN_SOFT_MIN_VERSION,
  DEVIN_STOP_CAP_RAISE_FOUND,
  probeDevinCliVersion,
  isParseableDevinVersion,
  isDevinVersionBelowSoftMin,
} from "./init/install.js";
export type { InitYesOptions, InitResult, HooksFile } from "./init/types.js";
export type {
  ClaudeSettingsFile,
  ClaudeMatcherGroup,
  ClaudeHookHandler,
} from "./init/claude-settings-merge.js";
export type {
  CodexHooksFile,
  CodexMatcherGroup,
  CodexHookHandler,
} from "./init/codex-hooks-merge.js";
export type {
  CopilotHooksFile,
  CopilotHookHandler,
  CopilotAutopilotEvent,
} from "./init/copilot-hooks-merge.js";
export type {
  GrokHooksFile,
  GrokMatcherGroup,
  GrokHookHandler,
  GrokAutopilotEvent,
} from "./init/grok-hooks-merge.js";
export type {
  GeminiSettingsFile,
  GeminiMatcherGroup,
  GeminiHookHandler,
  GeminiAutopilotEvent,
} from "./init/gemini-settings-merge.js";
export type {
  KimiHookEntry,
  KimiAutopilotEvent,
} from "./init/kimi-hooks-merge.js";
export type {
  HermesHookEntry,
  HermesAutopilotEvent,
  HermesConfigFile,
} from "./init/hermes-hooks-merge.js";
export type {
  DevinHooksFile,
  DevinMatcherGroup,
  DevinHookHandler,
} from "./init/devin-hooks-merge.js";
export type { PreflightResult } from "./init/install.js";
export { PACKAGE_VERSION } from "./init/types.js";
export { formatStatus, runDoctor, readPinVersion, readStaleAfterHours, hasGlobalSelfReviewHooks } from "./status-doctor.js";
export type { DoctorOptions, DoctorResult } from "./status-doctor.js";
export { upgradeProject } from "./upgrade.js";
export type { UpgradeOptions, UpgradeResult } from "./upgrade.js";
export { uninstallProject } from "./uninstall.js";
export type {
  UninstallOptions,
  UninstallResult,
} from "./uninstall.js";
export {
  mergeConfigYamlMissingKeys,
  mergeMissingKeys,
  readConfigInstallHints,
  readConfigPlatformsOrThrow,
} from "./init/config-merge.js";
export {
  collectWizardAnswers,
  runInteractiveInit,
} from "./init/tui.js";
export type { InitPrompts, InteractiveInitOptions } from "./init/tui.js";
export {
  probeProject,
  applyPlansGitignore,
  applyAutopilotRuntimeGitignore,
  answersToInstallOptions,
  formatCheatSheet,
  formatHostDisplayName,
  formatHostActivationTips,
  formatPostInstallOutro,
  formatPostInstallFooter,
  installableHostOptions,
  writeQuickstart,
  normalizePlansDir,
  parseInitReviewScope,
  resolveCliCommand,
  tryResolveRunningCliScript,
  autopilotShellAliasLine,
  assertNotSymlink,
  assertRealpathInside,
  assertPairInsideOrUnlinkAll,
  isRealRegularFile,
  isRealDirectory,
  resolveProjectRootOrThrow,
} from "./init/wizard-helpers.js";
export type {
  InitWizardAnswers,
  PlansGitPolicy,
  ShellAliasTarget,
} from "./init/wizard-helpers.js";
export {
  INSTALLABLE_BINDINGS,
  MAX_PLATFORM_BINDINGS,
  applyPlatformsToConfigYaml,
  assertInstallablePlatforms,
  configWantsAgentsSkills,
  configWantsInstallableHost,
  platformsWantAgentsSkills,
  platformsWantInstallableHost,
  configYamlHasLegacyHostScalars,
  defaultSurfaceFor,
  ensureRunnerConfigKeys,
  formatBindingOptionLabel,
  formatPlatformsDisplay,
  hasInstallableHookHost,
  isInstallableBinding,
  mergePlatformBindings,
  mergedIncludesAllRequested,
  normalizeBinding,
  parsePlatformBindingsFromConfig,
  parsePlatformsCliList,
  primaryBinding,
  sanitizePlatformId,
  stripRunnerConfigTraces,
  wantAgentsSkillsFromFlags,
} from "./init/platforms.js";
export type {
  HostSkillsParent,
  PlatformBinding,
  PlatformSurface,
} from "./init/platforms.js";
export {
  PI_PLATFORM,
  PI_SOFT_MIN_VERSION,
  PI_EXTENSION_REL_PATH,
  PI_EXTENSION_IGNORE_PATTERN,
  PI_EXTENSION_FINGERPRINTS,
  resolvePiExtensionTemplate,
  piExtensionAbsolutePath,
  piExtensionContainsAutopilot,
  readPiExtensionFile,
  installPiExtension,
  removePiExtension,
  probePiCliVersion,
  isPiVersionBelowSoftMin,
} from "./init/pi-extension.js";
export { setProjectLocale } from "./locale-set.js";
export type {
  LocaleSetOptions,
  LocaleSetResult,
} from "./locale-set.js";
export {
  formatSessionDisplayName,
  formatSessionList,
  purgeProjectSession,
  renameProjectSession,
  resetProjectSessionReview,
  shortSessionId,
} from "./session.js";
export type {
  SessionCmdResult,
  SessionListResult,
} from "./session.js";
export {
  formatRunnerStartSuccess,
  formatRunnerStatus,
  loadProjectRunnerSettings,
  resolveRunnerConfigForStart,
  startRunner,
  exitCodeForLoopResult,
} from "./runner-cli.js";
export type {
  RunnerCliFlagOverrides,
  RunnerStartOutcome,
} from "./runner-cli.js";
